// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dingwd.netty.study.grpc.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dingwd.netty.study.grpc.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   * @return The realname.
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 1;</code>
   * @return The bytes for realname.
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
