// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dingwd.netty.study.grpc.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dingwd.netty.study.grpc.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string real_name = 1;</code>
   * @return The realName.
   */
  java.lang.String getRealName();
  /**
   * <code>string real_name = 1;</code>
   * @return The bytes for realName.
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
