// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dingwd.netty.study.grpc.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dingwd.netty.study.grpc.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *集合用repeated表示
   * </pre>
   *
   * <code>repeated .com.dingwd.netty.study.grpc.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.dingwd.netty.study.grpc.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <pre>
   *集合用repeated表示
   * </pre>
   *
   * <code>repeated .com.dingwd.netty.study.grpc.StudentResponse studentResponse = 1;</code>
   */
  com.dingwd.netty.study.grpc.proto.StudentResponse getStudentResponse(int index);
  /**
   * <pre>
   *集合用repeated表示
   * </pre>
   *
   * <code>repeated .com.dingwd.netty.study.grpc.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <pre>
   *集合用repeated表示
   * </pre>
   *
   * <code>repeated .com.dingwd.netty.study.grpc.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.dingwd.netty.study.grpc.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <pre>
   *集合用repeated表示
   * </pre>
   *
   * <code>repeated .com.dingwd.netty.study.grpc.StudentResponse studentResponse = 1;</code>
   */
  com.dingwd.netty.study.grpc.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
