// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dingwd.netty.study.grpc.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dingwd_netty_study_grpc_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dingwd_netty_study_grpc_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dingwd_netty_study_grpc_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dingwd_netty_study_grpc_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dingwd_netty_study_grpc_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dingwd_netty_study_grpc_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dingwd_netty_study_grpc_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dingwd_netty_study_grpc_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dingwd_netty_study_grpc_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dingwd_netty_study_grpc_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dingwd_netty_study_grpc_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dingwd_netty_study_grpc_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dingwd_netty_study_grpc_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dingwd_netty_study_grpc_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\033com.dingwd.netty.study." +
      "grpc\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nM" +
      "yResponse\022\020\n\010realname\030\001 \001(\t\"\035\n\016StudentRe" +
      "quest\022\013\n\003age\030\001 \001(\005\":\n\017StudentResponse\022\014\n" +
      "\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"\\" +
      "\n\023StudentResponseList\022E\n\017studentResponse" +
      "\030\001 \003(\0132,.com.dingwd.netty.study.grpc.Stu" +
      "dentResponse\"%\n\rStreamRequest\022\024\n\014request" +
      "_info\030\001 \001(\t\"\'\n\016StreamResponse\022\025\n\rrespons" +
      "e_info\030\001 \001(\t2\341\003\n\016StudentService\022j\n\025GetRe" +
      "alNameByUsername\022&.com.dingwd.netty.stud" +
      "y.grpc.MyRequest\032\'.com.dingwd.netty.stud" +
      "y.grpc.MyResponse\"\000\022q\n\020GetStudentsByAge\022" +
      "+.com.dingwd.netty.study.grpc.StudentReq" +
      "uest\032,.com.dingwd.netty.study.grpc.Stude" +
      "ntResponse\"\0000\001\022|\n\027GetStudentsWrapperByAg" +
      "e\022+.com.dingwd.netty.study.grpc.StudentR" +
      "equest\0320.com.dingwd.netty.study.grpc.Stu" +
      "dentResponseList\"\000(\001\022r\n\021BidirectionalTal" +
      "k\022*.com.dingwd.netty.study.grpc.StreamRe" +
      "quest\032+.com.dingwd.netty.study.grpc.Stre" +
      "amResponse\"\000(\0010\001B3\n!com.dingwd.netty.stu" +
      "dy.grpc.protoB\014StudentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dingwd_netty_study_grpc_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dingwd_netty_study_grpc_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dingwd_netty_study_grpc_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_dingwd_netty_study_grpc_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dingwd_netty_study_grpc_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dingwd_netty_study_grpc_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_dingwd_netty_study_grpc_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_dingwd_netty_study_grpc_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dingwd_netty_study_grpc_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_dingwd_netty_study_grpc_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_dingwd_netty_study_grpc_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dingwd_netty_study_grpc_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_dingwd_netty_study_grpc_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_dingwd_netty_study_grpc_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dingwd_netty_study_grpc_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_com_dingwd_netty_study_grpc_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_dingwd_netty_study_grpc_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dingwd_netty_study_grpc_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_com_dingwd_netty_study_grpc_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_dingwd_netty_study_grpc_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dingwd_netty_study_grpc_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
